esphome:
  name: $devicename
  comment: ${device_description}
  platform: ESP8266
  board: d1_mini
  platformio_options:
    upload_speed: 115200


substitutions:
  devicename: vindriktning
  friendly_name: Ikea Vindriktning PM2.5 sensor
  device_description: Ikea luchtkwaliteitssensor
  
  
# Enable logging
logger:
  level: DEBUG
  
status_led:
  # Wemos uses GPIO2 for the built in LED
  pin:
    number: GPIO2
    # It needs an inversion (active low)
    inverted: True  

# Enable Home Assistant API & OTA Updates
api:
 encryption:
    key: !secret api_key_password
ota:
 password: !secret ota_password
 safe_mode: true
 reboot_timeout: 10min
 num_attempts: 5
 
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .lan
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: “${devicename} Fallback AP"
    password: !secret fallback_ap_password

captive_portal:

# Ikea Vindriktning PM2.5 sensor
uart:
  rx_pin: D4
  baud_rate: 9600
  
i2c:
  sda: D2
  scl: D1
  frequency: 200kHz
  
web_server:
  port: 80
  
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
    
  - platform: gpio
    pin: D7
    name: "${friendly_name}  Motion"
    device_class: motion
    filters:
      - delayed_off: 30s

    
sensor:
  - platform: pm1006
    pm_2_5:
      name: "${friendly_name} PM25"
      device_class: pm25
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 10   

  - platform: uptime
    name: "${friendly_name} Uptime"
    disabled_by_default: true
    entity_category: diagnostic    
    
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 240s
    disabled_by_default: true
    entity_category: diagnostic
    
  - platform: aht10
    temperature:
      name: "${friendly_name} Temperature"
      unit_of_measurement: "°C"
      device_class: temperature
      accuracy_decimals: 1
      filters:
      - filter_out: 0.0
      - median:
          window_size: 3
          send_every: 3
          send_first_at: 2
    humidity:
      name: "${friendly_name} Humidity"
      unit_of_measurement: "%"
      device_class: humidity
      accuracy_decimals: 2
      filters:
      - filter_out: 0.0
      - quantile:
          window_size: 6
          send_every: 3
          send_first_at: 1
          quantile: .9
    update_interval: 15s    
  
switch:
  - platform: restart
    name: "${friendly_name} restart"  
    entity_category: config